#!/bin/sh

# cumtos ntp
uci delete system.ntp.server
uci add_list system.ntp.server='ntp1.aliyun.com'
uci add_list system.ntp.server='ntp.tencent.com'
uci add_list system.ntp.server='ntp.ntsc.ac.cn'
uci add_list system.ntp.server='time.apple.com'
# uci set system.ntp.enable_server='1'
uci commit system

# set default theme
theme=argon
# theme=design
# theme=material
if [ -d "/www/luci-static/$theme" ]; then
    uci set luci.main.mediaurlbase=/luci-static/$theme
    uci commit luci
fi

# detect network version
new_net=true
if [ -n "$(uci -q get network.lan.type)" ]; then
    new_net=false
fi

# lan
uci delete network.lan.ip6assign
uci set network.lan.ipaddr='192.168.1.1'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.dns='223.5.5.5 114.114.114.114'

# add zerotier interface
if [ -f "/etc/config/zerotier" ]; then
    uci set network.zerotier=interface
    if $new_net; then
        uci set network.zerotier.device='zt5u4x7t2c'
    else
        uci set network.zerotier.ifname='zt5u4x7t2c'
    fi
    uci set network.zerotier.proto='none'
    uci set network.zerotier.delegate='0'
    uci set network.zerotier.auto='1'
    uci add_list firewall.@zone[0].network='zerotier'
fi

uci commit network
uci commit firewall

# disable redirect https
uci set uhttpd.main.redirect_https='0'
uci commit uhttpd

# remove feeds repository
sed -i '/helloworld/d' /etc/opkg/distfeeds.conf
sed -i '/passwall/d' /etc/opkg/distfeeds.conf

# move menu
sed -i 's/\"services\"/\"control\"/g' /usr/lib/lua/luci/controller/appfilter.lua
sed -i 's/\"services\"/\"control\"/g' /usr/lib/lua/luci/controller/mia.lua

# anti-ad auto update for smartdns
# if [ -f "/etc/smartdns/anti-ad.sh" ]; then
#     echo "0 5 * * * /etc/smartdns/anti-ad.sh > /dev/null 2>&1 &" >>/etc/crontabs/root
# fi

# rules auto update for mosdns
if [ -f "/etc/mosdns/update_rules.sh" ]; then
    echo "30 6 * * * /etc/mosdns/update_rules.sh" >>/etc/crontabs/root
fi

uci commit

exit 0
