#!/bin/sh

# wait network
sleep 10

# set default theme
uci set luci.main.mediaurlbase=/luci-static/argon
uci commit luci

# set lan ip
uci set network.lan.ipaddr='192.168.11.1'
uci set network.lan.netmask='255.255.255.0'
uci commit network

# remove feeds repository
sed -i '/helloworld/d' /etc/opkg/distfeeds.conf
sed -i '/diy1/d' /etc/opkg/distfeeds.conf
sed -i '/n2n/d' /etc/opkg/distfeeds.conf

ping -c 3 -w 5 192.168.11.2
ret_gw=$?
ping -c 3 -w 5 192.168.11.3
ret_ac=$?
if [ $ret_gw == 0 -a $ret_ac == 0 ]; then
    uci set network.globals.ula_prefix='fd66:6a59:d6ec::/48'

    uci delete network.lan.ip6assign
    uci set network.lan.gateway='192.168.11.2'
    uci set network.lan.dns='114.114.114.114 1.2.4.8'

    uci delete network.wan
    uci delete network.wan6

    uci set network.iptv=interface
    uci set network.iptv.proto='dhcp'
    uci set network.iptv.ifname='eth1'
    uci set network.iptv.defaultroute='0'

    uci set network.n2n0=interface
    uci set network.n2n0.proto='none'
    uci set network.n2n0.ifname='n2n0'
    uci set network.n2n0.delegate='0'

    uci commit network

    uci set dhcp.lan.ignore=1
    uci delete dhcp.lan.start
    uci delete dhcp.lan.limit
    uci delete dhcp.lan.leasetime
    uci delete dhcp.lan.dhcpv6
    uci delete dhcp.lan.ra
    uci commit dhcp

    uci set firewall.@zone[0].network='lan n2n0'
    uci set firewall.@zone[1].network='wan wan6 iptv'
    uci set firewall.@zone[1].input='ACCEPT'
    uci commit firewall
fi

exit 0
